### ISSUE TITLE
Add Drone weight/cfg/name files to build

### ISSUE THREAD

**Issue by rob-spotter** [harshiniKumar/Drone-Detection-using-YOLOv3#2]
Hi, can you add your drone training weight / cfg & name files to the build root. The links added don't work. Tnx.

**Comment by harshiniKumar** [comment]
Hi, here is the pretrained weights : [click](https://1drv.ms/u/s!AhwEgrisOm4yjnBvaBClgZXvhdDO?e=s9ytpm)
